Parallel shutdown using GNU parallel in goby_launch; avoid having basic simulator frontseat quit when disconnected from simulator TCP server which messes up a clean shutdown

diff --git a/scripts/goby_launch b/scripts/goby_launch
--- a/scripts/goby_launch
+++ b/scripts/goby_launch
@@ -34,6 +34,7 @@ usage()
     echo -e "\t-p vehicle1\tPlatform name"
     echo -e "\t-m 10\t\tDelay in seconds after sending goby_terminate before escalating to SIGTERM"
     echo -e "\t-k 10\t\tDelay in seconds after sending SIGTERM before escalating to SIGKILL"
+    echo -i "\t-P\tExecute kill commands in parallel"
 }
 
 num_running_proc()
@@ -55,6 +56,59 @@ check_launch_type_unset()
     [ "$launch" != screen ] && echo "Error: -r, -n, -t, -x, and -s are mutually exclusive. For help use -h." && exit 1
 }
 
+do_killone()
+{
+    p=$1
+    cmd=$2
+    sig=$3
+    gobyd_interprocess=$4
+    sigterm_delay=$5
+    sigkill_delay=$6
+    parallel=$7
+
+    
+    # don't kill anything that's already dead
+    kill -0 $p >& /dev/null || return
+
+    
+    if [ "$sig" = "goby_terminate" ]; then
+
+        if [ "$parallel" = true ]; then
+            # don't kill gobyd yet
+            echo $cmd | grep -q "^ *[/a-zA-Z0-9_]*gobyd" && return
+        fi
+        
+        # run goby_terminate to cleanly shutdown processes
+        echo -n "goby_terminate: $p (was $cmd)"
+        if goby_terminate --response_timeout ${sigterm_delay} --target_pid $p <(echo ${gobyd_interprocess});
+        then
+            echo -e " .... success"
+            return 0
+        fi
+        
+        sig=SIGTERM
+        # if goby_terminate failed, use SIGTERM, then SIGKILL
+        echo -e "\n=== WARNING ===: Process $p did not respond to goby_terminate, sending $sig"        
+    fi
+    
+    echo -n "$sig: $p (was $cmd)"
+    kill -$sig $p
+    
+    elapsed_ms=0
+    while $(kill -0 $p 2>/dev/null); do 
+        sleep 0.1
+        elapsed_ms=$(($elapsed_ms + 100))
+        # if necessary, escalate to SIGKILL
+        if (($elapsed_ms > $sigkill_delay)); then
+            echo -e "\n====== WARNING ======: Process $p did not respond to SIGTERM after $sigkill_delay ms, sending SIGKILL"
+            echo -n "SIGKILL: $p (was $cmd)"
+            kill -SIGKILL $p
+            break;
+        fi
+    done
+    echo -e " .... success"
+}
+
 do_kill()
 {
     # nothing to kill
@@ -64,50 +118,25 @@ do_kill()
     echo ""
     echo "Cleaning up..."
 
-    # send SIGTERM to all the child processes
-    for ((i=$((${#spid[@]}-1)); i>=0; --i)); do 
-        p=${spid[i]}
-        cmd=${spid_cmd[i]}
-        sig=${spid_sig[i]}
+    gobyd_interprocess_1line=$(echo "${gobyd_interprocess}" | tr '\n' ' ')
+    if [ "$parallel_shutdown" = true ]; then
+        echo "Excecuting parallel shutdown, but delaying quitting gobyd (if any)"
+        export -f do_killone
+        parallel --link do_killone ::: ${spid[@]} ::: "${spid_cmd[@]}" ::: ${spid_sig[@]} ::: "${gobyd_interprocess_1line}" ::: ${sigterm_delay} ::: ${sigkill_delay} ::: true
+    fi
 
-        kill -0 $p >& /dev/null || continue
-
-        if [ "$sig" = "goby_terminate" ]; then
-            # run goby_terminate to cleanly shutdown processes
-            echo -n "goby_terminate: $p (was $cmd)"
-            if goby_terminate --response_timeout ${sigterm_delay} --target_pid $p <(echo ${gobyd_interprocess});
-            then
-                echo -e " .... success"
-                continue
-            fi
-
-            sig=SIGTERM
-            # if goby_terminate failed, use SIGTERM, then SIGKILL
-            echo -e "\n=== WARNING ===: Process $p did not respond to goby_terminate, sending $sig"
-        fi
-        
-        echo -n "$sig: $p (was $cmd)"
-        kill -$sig $p
-
-        elapsed_ms=0
-        while $(kill -0 $p 2>/dev/null); do 
-            sleep 0.1
-            elapsed_ms=$(($elapsed_ms + 100))
-            # if necessary, escalate to SIGKILL
-            if (($elapsed_ms > $sigkill_delay)); then
-                echo -e "\n====== WARNING ======: Process $p did not respond to SIGTERM after $sigkill_delay ms, sending SIGKILL"
-                echo -n "SIGKILL: $p (was $cmd)"
-                kill -SIGKILL $p
-                break;
-            fi
-        done
-        echo -e " .... success"
-    done
-
+    # kill everything in non-parallel mode, or gobyd if left over in parallel mode
+    for ((i=$((${#spid[@]}-1)); i>=0; --i)); do
+        do_killone ${spid[i]} "${spid_cmd[i]}" ${spid_sig[i]} "${gobyd_interprocess_1line}" ${sigterm_delay} ${sigkill_delay} false
+    done       
+    
+    
     spid=()
 
     rm $launchfile;
-    
+
+    echo "[${platform}]: All processes exited"
+
     exit 0;
 }
 
@@ -120,8 +149,9 @@ background=false
 sigkill_delay=10000
 # in s
 sigterm_delay=10
+parallel_shutdown=false
 
-while getopts ":rhsnxd:bp:k:m:" opt; do
+while getopts ":rhsnxPd:bp:k:m:" opt; do
     case $opt in
         h) usage; exit 1 ;;
         r) check_launch_type_unset; launch=normal ;;
@@ -134,6 +164,7 @@ while getopts ":rhsnxd:bp:k:m:" opt; do
         b) background=true ;;
         k) sigkill_delay=$(($OPTARG*1000)) ;;
         m) sigterm_delay=$OPTARG ;;
+        P) parallel_shutdown=true ;;
         \?)
             echo "Invalid option: -$OPTARG. For help use -h."
             exit  1
@@ -340,7 +371,6 @@ if [ "$background" = false ]; then
         fi
         sleep 5            
     done
-    echo "[${platform}]: All processes exited"
 else
     if [ $launch = "gnometerm" ]; then 
         echo -e "To quit, close the gnome-terminal window(s)"
